
# 動作モードの設定
# NORMAL or ONLY_ONE
# ONLY_ONEに設定した場合は全てのプレイヤーに対して同じParallelWorldが使われるようになります
work-type: NORMAL


# パフォーマンスモードを使用するかどうかの設定
# このプラグイン以外でブロックの設置が行われる可能性のある場合は false 推奨
performance-mode: false


## ライトパケットへの介入を行うかどうかの設定
rewrite-light-packet: true